Repository python/python-docs-tr, pull requests merged in 2023-01, with the labels that each got.

#89 Translate howto/index
  howto/index.po
Labels: new-translation

#91 Wrap branch: installing-index
  installing/index.po
Labels: wrap

#90 machine translated: installing/index
  installing/index.po
Labels: new-translation, machine-translated

#93 ceviri oncesi rezervasyon adimlari eklendi
  README.md
Labels: misc

#88 machine translated: c-api/index
  c-api/index.po
Labels: new-translation, machine-translated

#100 Wrap branch: 3.11
  howto/index.po
Labels: wrap
