Repository python/python-docs-tr, pull requests merged in 2023-12, with the labels that each got.

#163 Translation Update 3.12
  Makefile
  bugs.po
  c-api/set.po
  extending/newtypes.po
  glossary.po
  howto/descriptor.po
  howto/enum.po
  howto/isolating-extensions.po
  howto/perf_profiling.po
  howto/pyporting.po
  library/asyncio-stream.po
  library/cmdline.po
  library/contextlib.po
  library/datetime.po
  library/doctest.po
  library/email.errors.po
  library/functions.po
  library/gzip.po
  library/importlib.resources.po
  library/profile.po
  library/socket.po
  library/sqlite3.po
  library/stdtypes.po
  library/sys.monitoring.po
  library/test.po
  library/tkinter.po
  library/tkinter.ttk.po
  library/typing.po
  library/unittest.po
  library/xml.po
  reference/expressions.po
  tutorial/errors.po
  using/configure.po
  whatsnew/2.0.po
  whatsnew/2.7.po
  whatsnew/3.12.po
Labels: update

#164 Wrap branch: 3.12
  library/functions.po
Labels: wrap

#167 Update distributing/index.po
  distributing/index.po
Labels: updated-translation
