Repository python/python-docs-tr, pull requests merged in 2023-02, with the labels that each got.

#103 Hello Read the Docs
  .gitignore
  .readthedocs.yaml
Labels: misc

#105 Wrap branch: fix-fuzzys
  library/functions.po
  library/stdtypes.po
Labels: wrap

#106 Fix fuzzy entries introduced with #87
  extending/index.po
  installing/index.po
  library/functions.po
  library/stdtypes.po
  tutorial/classes.po
Labels: wrap, updated-translation, bug

#102 tamamlandı: whatsnew-3.8
  whatsnew/3.8.po
Labels: new-translation

#110 Update Makefile
  Makefile
Labels: misc

#114 Translate library/urllib.po
  library/urllib.po
Labels: new-translation

#75 translated whatsnew 3.9
  whatsnew/3.9.po
Labels: new-translation

#115 Wrap branch: 3.11
  library/urllib.po
  tutorial/venv.po
  whatsnew/3.9.po
Labels: wrap

#117 Translate library/tk.po to Turkish
  library/tk.po
Labels: new-translation

#121 Wrap branch: 3.11
  library/tk.po
Labels: wrap

#125 Library time
  TRANSLATORS
  library/time.po
Labels: new-translation
