Repository python/python-docs-tr, pull requests merged in 2023-05, with the labels that each got.

#143 Tamamlandı: clinic.po
  howto/clinic.po
Labels: new-translation

#144 New progress script + New translation
  .pre-commit-config.yaml
  includes/wasm-notavail.po
  merge.py
  scripts/format_check.py
  scripts/progress.py
  scripts/translate.py
Labels: new-translation, misc, pre-commit

#147 Wrap branch: 3.11
  howto/clinic.po
  library/math.po
Labels: wrap
