Repository python/python-docs-tr, pull requests merged in 2024-04, with the labels that each got.

#183 Translation Update 3.12
  Makefile
  c-api/contextvars.po
  c-api/import.po
  c-api/init.po
  c-api/refcounting.po
  c-api/structures.po
  faq/design.po
  faq/extending.po
  faq/general.po
  glossary.po
  howto/logging-cookbook.po
  howto/logging.po
  library/asyncio-eventloop.po
  library/audit_events.po
  library/bz2.po
  library/ctypes.po
  library/dataclasses.po
  library/decimal.po
  library/dis.po
  library/enum.po
  library/faulthandler.po
  library/functools.po
  library/hashlib.po
  library/http.server.po
  library/idle.po
  library/importlib.metadata.po
  library/inspect.po
  library/ipaddress.po
  library/itertools.po
  library/logging.po
  library/math.po
  library/os.po
  library/pdb.po
  library/pprint.po
  library/pydoc.po
  library/pyexpat.po
  library/resource.po
  library/ssl.po
  library/statistics.po
  library/stdtypes.po
  library/threading.po
  library/time.po
  library/typing.po
  library/unittest.mock.po
  library/urllib.request.po
  library/venv.po
  library/xml.etree.elementtree.po
  reference/datamodel.po
  reference/lexical_analysis.po
  reference/simple_stmts.po
  sphinx.po
  tutorial/errors.po
  tutorial/introduction.po
  using/cmdline.po
  using/configure.po
  using/mac.po
Labels: update

#185 Update tutorial/modules
  tutorial/modules.po
Labels: wrap, updated-translation

#186 Wrap branch: 3.12
  tutorial/modules.po
Labels: wrap

#187 Update on library/datetime.po
  library/datetime.po
Labels: updated-translation
